version: "3"

services:

  nginx:
    build:
      context: ./nginx
    container_name: ${PROJECT_NAME}--nginx-rp
    image: ${IMAGE_NAME}-nginx
    ports:
      - '85:85'
    depends_on:
      - django
      - angular

  angular:
    build:
      context: ./angular
    container_name: ${PROJECT_NAME}--angular-front
    image: ${IMAGE_NAME}-angular
    ports:
      - '80:80'
    volumes:
      # - ./angular/dist/ng7:/var/www/html
      - ./config/apache/angular-000-default.conf:/etc/apache2/sites-available/000-default.conf

  django:
    build:
      context: ./django
    container_name: ${PROJECT_NAME}--django-api
    image: ${IMAGE_NAME}-django
    ports:
      - '8000'
    depends_on:
      - postgres
  
  postgres:
    build:
      context: ./postgres
    container_name: ${PROJECT_NAME}--postgres-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}